WIP: RM - Add Guide Message
TIP-Global-Health/eheza-app pull request #1105
Opened 2024-04-06 09:08 UTC by Diama1

#1102

2024-04-09 14:27 UTC, Diama1 commented
![ezgif com-video-to-gif-converter](https://github.com/TIP-Global-Health/eheza-app/assets/32199791/2aadebe7-08ec-4274-9d8e-b8e012e671ee)

2024-04-10 06:27 UTC, anvmn requested changes
.

2024-04-10 06:27 UTC, anvmn commented on client/src/elm/Backend/ResilienceMessage/Model.elm
> +    = ResilienceCategoryGuide
Guide is not a category of message. Guide constant. Revert and use different approach.

2024-05-15 12:01 UTC, anvmn requested changes

2024-05-15 12:01 UTC, anvmn commented on client/src/elm/Pages/MessagingCenter/View.elm
> +            model.activeTab == TabGuide
Seems wrong. This is not where you set default active tab.

2024-05-15 12:01 UTC, anvmn commented on client/src/elm/Pages/MessagingCenter/View.elm
> +                    div []
Seems wrong

2024-05-15 12:01 UTC, anvmn commented on client/src/elm/Pages/MessagingCenter/View.elm
> +            --
remove

2024-05-15 12:01 UTC, anvmn commented on client/src/elm/Translate.elm
> +    | ResilienceMessageGuide
There are no messages in Guide.
Message is an entity that can be read, set as favourite, etc..
Guide contains sections.

`ResilienceMessageGuide` => `Guide`

2024-05-15 12:01 UTC, anvmn commented on client/src/elm/Translate.elm
> +    | ResilienceMessageGuideTitle1
This and all bellow => 

`ResilienceMessageGuideXXX` =>  `ResilienceGuideSectionXXX`

2024-05-15 12:01 UTC, anvmn commented on client/src/elm/Translate.elm
> +                    { english = "Guide"
=> `translationSet Guide`

2024-05-15 12:01 UTC, anvmn commented on server/hedley/modules/custom/hedley_resilience/hedley_resilience.features.field_base.inc
> +        'guide' => 'Guide',
Not needed

2024-05-29 19:38 UTC, anvmn approved these changes

2024-05-30 07:54 UTC, merged