RM - Fix the style on guide
TIP-Global-Health/eheza-app pull request #1192
Opened 2024-06-03 16:15 UTC by Diama1

#1191

2024-06-04 18:28 UTC, adamhstewart commented
@Diama1 can you provide screenshots to show the changes?

2024-06-04 18:34 UTC, adamhstewart commented
@Diama1 Also, pretty sure this should go against https://github.com/TIP-Global-Health/eheza-app/pull/1159 before it is merged to the develop branch.

2024-06-05 02:29 UTC, AronNovak approved these changes

2024-06-10 10:09 UTC, Diama1 commented
> @Diama1 Also, pretty sure this should go against #1159 before it is merged to the develop branch.

@adamhstewart develop branch has the latest changes, the one I worked on that's why I branch out there. the other one is not yet merged and doesn't have the latest changes

2024-06-10 10:16 UTC, Diama1 commented
> @Diama1 can you provide screenshots to show the changes?

![Screenshot from 2024-06-10 12-10-05](https://github.com/TIP-Global-Health/eheza-app/assets/32199791/901da82d-0564-499d-842f-8b563dbfe30a)
![onload](https://github.com/TIP-Global-Health/eheza-app/assets/32199791/246db79b-353d-4224-b46a-2495cbddc19e)
![whole](https://github.com/TIP-Global-Health/eheza-app/assets/32199791/ae6723dc-5c14-4f99-a7e8-ddc40425b072)

2024-06-11 03:10 UTC, AronNovak commented on client/src/elm/Translate.elm
> +                    , kinyarwanda = Nothing
Why do we remove a translation? Is it wrong? Can't we have the good one?

2024-06-11 03:11 UTC, AronNovak commented on client/src/elm/Translate.elm
> +            , kinyarwanda = Nothing
same here

2024-06-13 09:44 UTC, anvmn requested changes

2024-06-13 09:44 UTC, anvmn commented on client/src/elm/Pages/MessagingCenter/View.elm
> +                        |> Maybe.withDefault messagingCenterView
@Diama1 This means that if nurse got no surveys filled, we will never ask to fill any survey.
So, this change is incorrect.

2024-06-20 20:34 UTC, anvmn commented
Moved to #1159. Closing.

2024-06-20 20:34 UTC, closed without merging