Resilience message - repositioning and rephrasing the guide message
TIP-Global-Health/eheza-app pull request #1244
Opened 2024-07-09 18:32 UTC by Diama1

#1243

2024-07-11 11:39 UTC, Diama1 commented
![guidemessage](https://github.com/TIP-Global-Health/eheza-app/assets/32199791/b0280b44-0518-42a5-bfa3-11558424a869)

2024-07-15 13:56 UTC, anvmn requested changes

2024-07-15 13:56 UTC, anvmn commented on client/src/elm/Pages/Page.elm
> +    | GuideMessagePage
Call the page `MessagingGuide`.

2024-07-15 13:56 UTC, anvmn commented on client/src/elm/Pages/Router.elm
> +                    Just "guide"
=> `messaging-guide`

2024-07-15 13:56 UTC, anvmn commented on client/src/elm/Pages/Router.elm
> +        , map (UserPage GuideMessagePage) (s "guide")
=> `messaging-guide`

2024-07-15 13:56 UTC, anvmn commented on client/src/assets/scss/_new.scss
> +div.page-activity.guideMessage {
=> `messaging-guide`

2024-07-15 13:56 UTC, anvmn commented on client/src/elm/Pages/GuideMessage/View.elm
> +    div [ class "page-activity guideMessage" ]
=> `messaging-guide`

2024-07-15 13:56 UTC, anvmn commented on client/src/elm/Pages/GuideMessage/View.elm
> +module Pages.GuideMessage.View exposing (..)
=> `MessagingGuide`

2024-07-15 13:56 UTC, anvmn commented on client/src/elm/Pages/GuideMessage/View.elm
> +view : Language -> Time.Posix -> NurseId -> Nurse -> ModelIndexedDb -> Model -> Html Msg
You don't use anything besides `Languages`.

`view : Language -> Html Msg`

2024-07-16 07:10 UTC, anvmn requested changes

2024-07-16 07:10 UTC, anvmn commented on client/src/elm/App/Fetch.elm
> +            UserPage MessagingGuide ->
As this page presents constant text, there's not need to fetch anything.
So, all this logic should be replaced by `[]`.

2024-07-16 07:10 UTC, anvmn commented on client/src/elm/App/View.elm
> +                            |> Html.map (MsgLoggedIn << MsgPageMessagingCenter nurseId)
Only Msg page needs is `SetActivePage`, which can be used at top level (App.Model).
No need to make use of MessagingCenter page for that. 

See example of Clinical page:

![Selection_722](https://github.com/user-attachments/assets/043d7281-d939-4530-864a-d7baa36f0ea8)
![Selection_721](https://github.com/user-attachments/assets/1c6fe1a8-4d81-4069-a1e6-28a9bb152955)

2024-07-16 07:10 UTC, anvmn commented on client/src/elm/Pages/MessagingGuide/View.elm
> +import Pages.MessagingCenter.Model exposing (..)
drop

2024-07-16 07:10 UTC, anvmn commented on client/src/elm/Pages/MessagingGuide/View.elm
> +import Pages.MessagingCenter.Utils exposing (..)
drop

2024-07-16 16:20 UTC, anvmn approved these changes

2024-07-17 13:38 UTC, merged