Resilience Message - Correct Translations
TIP-Global-Health/eheza-app pull request #1268
Opened 2024-08-01 13:03 UTC by Diama1

#1265

2024-08-01 13:04 UTC, Diama1 commented
![Screenshot from 2024-08-01 14-55-21](https://github.com/user-attachments/assets/6d044987-b1eb-42f0-8bd9-4d9fde438903)
![Screenshot from 2024-08-01 14-55-38](https://github.com/user-attachments/assets/64f82161-5e68-4cba-9984-662adffd4e07)
![Screenshot from 2024-08-01 14-56-22](https://github.com/user-attachments/assets/e1501e19-b402-4c74-9264-51be226fe6c7)
![Screenshot from 2024-08-01 14-56-35](https://github.com/user-attachments/assets/eaf10139-f571-4530-9430-14502eff5cfe)

2024-08-04 11:19 UTC, anvmn requested changes
@Diama1 

To prevent duplication, define standalone translation and use `translationSet` (see `Never` as example):
![Selection_763](https://github.com/user-attachments/assets/b550758c-37d5-40d5-b13c-78cd724b57d9)

Make this for following:

![Selection_755](https://github.com/user-attachments/assets/c527da76-19cf-4bbc-aebb-91fe30f33d15)
![Selection_757](https://github.com/user-attachments/assets/62b9e520-a3dc-438c-b4ab-1cdb155a17fd)

![Selection_756](https://github.com/user-attachments/assets/50d14743-b34f-444f-abe7-b74c08d2c122)

![Selection_758](https://github.com/user-attachments/assets/a9681e73-8c63-4649-9c98-90942e0af478)

![Selection_759](https://github.com/user-attachments/assets/4deeb450-10b1-4cfa-a623-951a288d3630)
![Selection_760](https://github.com/user-attachments/assets/06a734a8-68de-44ca-a12f-07ffe70dc1e7)

![Selection_761](https://github.com/user-attachments/assets/67c08198-a314-4921-a262-c1e6ff60749d)


![Selection_762](https://github.com/user-attachments/assets/d7521e7d-c1a7-4a2e-b480-110aa0a511dd)

2024-08-05 06:59 UTC, anvmn requested changes

2024-08-05 06:59 UTC, anvmn commented on client/src/elm/Translate.elm
> +    | AlmostEverydayOption
Drop the `Option` suffix, here, and everywhere bellow.

General  note - if you decide on standard, it should be implemented everywhere.
So, if you decided to have `Option` suffix, there should not be sets without it.

2024-08-07 13:50 UTC, anvmn approved these changes

2024-08-08 11:50 UTC, merged