WIP - Make Family Ubudehe Question Optional
TIP-Global-Health/eheza-app pull request #1328
Opened 2024-09-19 08:52 UTC by Diama1

#1307

2024-09-19 09:42 UTC, Diama1 commented
[ubudehe.webm](https://github.com/user-attachments/assets/f87f5b4c-bf6e-4e5b-a122-61c30187460d)

2024-09-22 07:10 UTC, anvmn requested changes
@Diama1 ^^

2024-09-22 07:10 UTC, anvmn commented on client/src/elm/Activity/Utils.elm
> +                                                |> Maybe.map (\_ -> True)
If there's no more dependency on Ubudehe, and every mother should get it, drop the condition.

2024-09-23 06:49 UTC, Diama1 commented on client/src/elm/Activity/Utils.elm
> +                                                |> Maybe.map (\_ -> True)
@anvmn there is no dependency on Ubudehe

2024-09-23 06:52 UTC, anvmn commented on client/src/elm/Activity/Utils.elm
> +                                                |> Maybe.map (\_ -> True)
@Diama1 then drop the condition

2024-09-23 07:53 UTC, anvmn commented on client/src/elm/Activity/Utils.elm
> +                                    isBreastfeeding
@Diama1 now we don't need to have it as a param.
Remove the `let`, and apply logic directly.

2024-09-23 20:00 UTC, anvmn approved these changes

2024-09-23 20:00 UTC, merged