Group Encounter - Display specific Messaging on Caregiver Activity
TIP-Global-Health/eheza-app pull request #302
Opened 2022-06-22 20:41 UTC by Diama1

[#2006](https://github.com/Gizra/ihangane/issues/2006)

2022-06-22 20:41 UTC, Diama1 commented
![Screenshot from 2022-06-22 22-38-34](https://user-images.githubusercontent.com/32199791/175132165-59fe22ea-3651-4153-b9e3-f8689b58d9cb.png)

2022-06-27 09:52 UTC, anvmn requested changes

2022-06-27 09:52 UTC, anvmn commented on client/src/elm/Pages/Participant/View.elm
> +viewActivityCards config language session ( motherId, mother ) activities selectedTab clinicType selectedActivity =
Why `(motherId, mother)`? It's used both for adults and children.
Signiture should be:
```
viewActivityCards :
    Participant id value activity msg NominalDate
    -> Language
    -> OfflineSession
    -> PersonId
    -> CompletedAndPending (List activity)
    -> Tab
    -> Maybe activity
    -> List ( String, Html (Msg activity any) )
viewActivityCards config language offlineSession personId activities selectedTab selectedActivity =
    let 
        clinicType == 
          offlineSession.session.clinicType
         ...
```

2022-07-04 11:20 UTC, anvmn commented
@Diama1 

What's the status?

2023-09-06 19:07 UTC, anvmn approved these changes

2023-09-06 19:20 UTC, merged