ANC - Remove the instruction Text on Symptom review activity
TIP-Global-Health/eheza-app pull request #388
Opened 2022-08-03 13:24 UTC by Diama1

[#325 Comment](https://github.com/TIP-Global-Health/eheza-app/issues/325#issuecomment-1191534837)

2022-08-03 13:24 UTC, Diama1 commented
![Screenshot from 2022-08-03 15-02-32](https://user-images.githubusercontent.com/32199791/182618887-4e4497df-8e97-4913-9b74-f24475f5cd01.png)

2022-08-07 09:19 UTC, anvmn requested changes

2022-08-07 09:19 UTC, anvmn commented on client/src/elm/Pages/Prenatal/Activity/View.elm
> -                div [ class "instructions" ]
@Diama1 This removes the label from both screens of activty.
It should be removed only from first screen.

![Peek 2022-08-07 12-18](https://user-images.githubusercontent.com/17882245/183284048-36a05547-a7e8-42c2-9a16-131f8a584455.gif)

2022-08-23 09:22 UTC, Diama1 commented
![imagepp](https://user-images.githubusercontent.com/32199791/186122311-dceebfcc-cf93-433f-b509-22010667c5f4.gif)

2022-08-24 07:59 UTC, anvmn requested changes
@Diama1 

Condition shoud be if to show or not:

```
div [ class "instructions" ]
     [ viewLabel language Translate.PrenatalSymptomQuestionsHeader ]
```

2022-08-24 07:59 UTC, anvmn commented on client/src/elm/Pages/Prenatal/Activity/View.elm
> +                    [ div [ class "ui form symptom-review" ] <|
Code duplication.

2022-08-24 08:44 UTC, anvmn approved these changes
:+1:

2022-08-24 08:45 UTC, merged