WIP: ANC PostPartum - Speciality Care
TIP-Global-Health/eheza-app pull request #428
Opened 2022-08-17 19:02 UTC by anvmn

#376
#377

2022-08-18 08:46 UTC, anvmn commented
![Peek 2022-08-18 11-44](https://user-images.githubusercontent.com/17882245/185352547-5048c555-789b-466a-9301-e60aa365246b.gif)

2022-08-22 13:15 UTC, anvmn commented
@mariano-dagostino please review

2022-08-22 14:19 UTC, mariano-dagostino requested changes
@anvmn Looks good. I found several places where user facing `Speciality` strings needs to be changed to `Specialty`

2022-08-22 14:19 UTC, mariano-dagostino commented on client/src/elm/SyncManager/View.elm
> +                viewMeasurement identifier "Prenatal Speciality Care"
`Specialty`

2022-08-22 14:19 UTC, mariano-dagostino commented on server/hedley/modules/custom/hedley_prenatal/hedley_prenatal.features.field_instance.inc
> +    'label' => 'Speciality Care Signs',
`Specialty`

2022-08-22 14:19 UTC, mariano-dagostino commented on server/hedley/modules/custom/hedley_prenatal/hedley_prenatal.features.field_instance.inc
> +  t('Speciality Care Signs');
`Specialty`

2022-08-22 14:19 UTC, mariano-dagostino commented on server/hedley/modules/custom/hedley_prenatal/hedley_prenatal.features.inc
> +      'name' => t('Prenatal Speciality Care'),
`Specialty`

2022-08-22 14:19 UTC, mariano-dagostino commented on server/hedley/modules/custom/hedley_restful/plugins/restful/node/activity/prenatal-speciality-care.inc
> +  'label' => t('Prenatal Speciality Care'),
`Specialty`

2022-08-22 14:19 UTC, mariano-dagostino commented on server/hedley/modules/custom/hedley_restful/plugins/restful/node/activity/prenatal-speciality-care.inc
> +  'description' => t('Exports the Prenatal Speciality Care bundle.'),
`Specialty`

2022-08-24 08:37 UTC, anvmn commented
All review comments addressed. Merging...

2022-08-24 08:37 UTC, merged