WIP: Patient Record & ANC Subs Translations
TIP-Global-Health/eheza-app pull request #436
Opened 2022-08-24 08:09 UTC by Diama1

#385
#384

2022-08-26 07:25 UTC, Diama1 commented
![Screenshot from 2022-08-26 09-23-54](https://user-images.githubusercontent.com/32199791/186846358-1db103fc-c70d-4866-9e47-2805380e7e9c.png)

2022-09-14 18:26 UTC, anvmn requested changes

2022-09-14 18:26 UTC, anvmn commented on client/src/elm/Translate.elm
> +            , kinyarwanda = Just "Ku rindi vuriro wagiyeho ugahabwa imiti. Ni iyihe miti wahawe"
Seems to me we need `?` at the end

2022-09-14 18:26 UTC, anvmn commented on client/src/elm/Translate.elm
> +            , kinyarwanda = Just "Icyitonderwa:Ni ngombwa kuvura uwo babana/bashakanye"
Add space after `:`

2022-09-14 18:26 UTC, anvmn commented on client/src/elm/Translate.elm
> +                    , kinyarwanda = Just "Witanga umuti. Kurikiza amabwiriza ajyanye n'inyigisho z'buzima"
Should end with `.`

2022-09-14 18:26 UTC, anvmn commented on client/src/elm/Translate.elm
> +                    , kinyarwanda = Just "Erythromicine"
This is wrong

2022-09-14 18:26 UTC, anvmn commented on client/src/elm/Translate.elm
> +                    , kinyarwanda = Just "Azithromycine"
This is wrong

2022-09-14 18:26 UTC, anvmn commented on client/src/elm/Translate.elm
> +                    , kinyarwanda = Just "Mu kanwa inshuro enye ku munsi mu minsi 14"
I think that whatever starts with small letter in English should start with small letter as well.
If I'm right, change, if not, ignore.

2022-09-14 18:26 UTC, anvmn commented on client/src/elm/Translate.elm
> +                    , kinyarwanda = Just "Kunywa ikinini 1 inshuro ku munsi mu minsi 7"
start with small letter

2022-09-14 18:26 UTC, anvmn commented on client/src/elm/Translate.elm
> +                    , kinyarwanda = Just "Mu kanwa inshuro 2 ku munsi mu minsi 7"
start with small letter

2022-09-14 18:26 UTC, anvmn commented on client/src/elm/Translate.elm
> +                    , kinyarwanda = Just "Mu kanwa inshuro 3 ku munsi mu minsi 7"
start with small letter

2022-09-14 18:26 UTC, anvmn commented on client/src/elm/Translate.elm
> +                    , kinyarwanda = Just "Mu gitsina buri joro mu majoro 3"
start with small letter

2022-09-14 18:26 UTC, anvmn commented on client/src/elm/Translate.elm
> +                    , kinyarwanda = Just "Inshuro imwe mu gitsina"
start with small letter

2022-09-14 18:26 UTC, anvmn commented on client/src/elm/Translate.elm
> +                    , kinyarwanda = Just "Mu kanwa inshuro 2 ku munsi"
start with small letter

2022-09-14 18:26 UTC, anvmn commented on client/src/elm/Translate.elm
> +                    , kinyarwanda = Just "Mu kanwa inshuro 3 ku munsi"
start with small letter

2022-09-14 18:26 UTC, anvmn commented on client/src/elm/Translate.elm
> +                    , kinyarwanda = Just "Mu kanwa inshuro 4 ku munsi"
start with small letter

2022-09-14 18:26 UTC, anvmn commented on client/src/elm/Translate.elm
> +                    , kinyarwanda = Just "Mu kanwa inshuro 2 ku munsi"
start with small letter

2022-09-14 18:26 UTC, anvmn commented on client/src/elm/Translate.elm
> +                    , kinyarwanda = Just "Mu kanwa inshuro 1 ku munsi"
start with small letter

2022-09-14 18:26 UTC, anvmn commented on client/src/elm/Translate.elm
> +                    , kinyarwanda = Just "Azithromycine"
This is wrong

2022-09-14 18:26 UTC, anvmn commented on client/src/elm/Translate.elm
> +                    , kinyarwanda = Just "Erythromicine"
This is wrong

2022-09-14 18:26 UTC, anvmn commented on client/src/elm/Translate.elm
> +                    , kinyarwanda = Just "Mu isura rishize wahawe AL (Kowaritemu), ibibini bine (4) byo kunywa mu kanwa inshuri ebyiri ku munsi mu minsi itatu"
should end with `.`

2022-09-20 11:20 UTC, anvmn approved these changes

2022-09-20 11:20 UTC, merged