Change logic on medication
TIP-Global-Health/eheza-app pull request #47
Opened 2021-12-16 13:21 UTC by Diama1

2021-12-16 22:18 UTC, anvmn requested changes
@Diama1 

One comment  + add a screenshot please.

2021-12-16 22:18 UTC, anvmn commented on client/src/elm/Pages/WellChildActivity/View.elm
> +                , div [ class <| "cell next-due " ++ nextDueClass ]
Use `classList`

2021-12-17 11:14 UTC, Diama1 commented
![Screen Shot 2021-12-17 at 13 11 18](https://user-images.githubusercontent.com/32199791/146536392-3a973a6f-9037-4c53-a486-300ddb1df273.png)
![Screen Shot 2021-12-16 at 14 43 09](https://user-images.githubusercontent.com/32199791/146536450-c147d200-7a62-49b4-804b-ea24a04f817b.png)
![Screen Shot 2021-12-16 at 14 44 51](https://user-images.githubusercontent.com/32199791/146536458-9c9d4867-a6af-4423-82b8-326f10b390bc.png)

2021-12-17 18:11 UTC, anvmn approved these changes
Thanks @Diama1

2021-12-17 18:11 UTC, merged