WIP: Onboarding improvements - development workflow
TIP-Global-Health/eheza-app pull request #490
Opened 2022-09-23 07:17 UTC by AronNovak

#486

2022-09-23 07:36 UTC, AronNovak commented
^^ GitPod app integration is back

2022-09-23 08:26 UTC, AronNovak commented
![image](https://user-images.githubusercontent.com/114076/191920594-1499b312-872f-49ca-8eaa-8931004cf60d.png)

2022-09-23 09:08 UTC, AronNovak commented
![image](https://user-images.githubusercontent.com/114076/191928043-c85f0214-0482-44c1-aa23-557278399928.png)

2022-09-23 09:22 UTC, AronNovak commented
It's not yet perfect, contacted GitPod support on port visibility issues.

2022-10-13 08:54 UTC, AronNovak commented
@anvmn It's half-ways.. GitPod is usable, however not 100%, and could not yet gain proper access to a Mac to work on the compatibility, working via CircleCI is highly ineffective for such a work, so I wait for ScaleWay to buy some more mac minis that I can use in the cloud :)

However finally we have much better PHP 7.4 compatibility as the tests are executed inside DDEV and uses PHP 7.4, not some older version.

2022-10-19 17:36 UTC, anvmn requested changes
@AronNovak 

Something strange. PR says that README.md requires re-roll, but:

![Selection_1175](https://user-images.githubusercontent.com/17882245/196764329-fa6e3f89-47e4-4d90-b107-12d87545f8c0.png)

2022-10-19 17:36 UTC, anvmn commented on README.md
> +1. Choose "Remote Explorer" on the left and open port 3000 too, either in new browser window or in preview.
Here and bellow, indexes do not increase for some reason.
We got:
```
1.
1.
1.
...
```

2022-10-20 04:43 UTC, AronNovak commented on README.md
> +1. Choose "Remote Explorer" on the left and open port 3000 too, either in new browser window or in preview.
See https://www.markdownguide.org/basic-syntax/#ordered-lists - it's a technique to avoid re-writing numbers if you inject items.

2022-10-20 07:14 UTC, anvmn approved these changes
@AronNovak 

Shall we merge it?

2022-10-28 06:45 UTC, merged