Change the well being icon
TIP-Global-Health/eheza-app pull request #667
Opened 2023-03-08 11:48 UTC by Diama1

#665

2023-03-08 11:49 UTC, Diama1 commented
![Screenshot from 2023-03-08 13-40-19](https://user-images.githubusercontent.com/32199791/223705789-0f02a27b-f025-4302-b5c7-88d1c3ef3a94.png)

2023-03-11 20:52 UTC, anvmn requested changes

2023-03-11 20:52 UTC, anvmn commented on client/src/elm/Pages/MessagingCenter/View.elm
> +                        [ img [ src "assets/images/wellbeing.svg" ] []
Why?

2023-04-10 08:27 UTC, anvmn commented on client/src/assets/images/envelope.svg
@Diama1 Can yu revert this please. There should be no changes here.

2023-04-11 10:40 UTC, Diama1 commented on client/src/assets/images/envelope.svg
@anvmn  I deleted it in the previous commit then when you gave a comment, I realized that it was being used some where else I put it back

2023-06-01 07:03 UTC, anvmn approved these changes

2023-06-01 07:04 UTC, merged