RM - Created Nested Entry
TIP-Global-Health/eheza-app pull request #717
Opened 2023-05-17 10:30 UTC by Diama1

#674

2023-05-23 11:48 UTC, Diama1 commented
![wellBeing](https://github.com/TIP-Global-Health/eheza-app/assets/32199791/ae11d7a8-bdc8-4a27-9fbe-95cf079d92c1)

2023-05-29 13:07 UTC, anvmn requested changes

2023-05-29 13:07 UTC, anvmn commented on client/src/assets/scss/_new.scss
> +div.page-activity.well-being{
Add space before `{`

2023-05-29 13:07 UTC, anvmn commented on client/src/assets/scss/_new.scss
> +div.page-activity.messaging-center{
Add space before `{`

2023-05-29 13:07 UTC, anvmn commented on client/src/elm/Translate.elm
> +                    { english = "WellBeing"
=> `Wellbeing`

2023-05-29 13:07 UTC, anvmn commented on client/src/elm/Pages/PinCode/Model.elm
> +    | MenuWellBeing
=> `MenuWellbeing`

2023-05-29 13:07 UTC, anvmn commented on client/src/elm/Pages/Page.elm
> +    | WellBeingPage
=> `WellbeingPage`

2023-05-29 17:36 UTC, anvmn requested changes

2023-05-29 17:36 UTC, anvmn commented on client/src/elm/Pages/Router.elm
> +        , map (UserPage WellBeingPage) (s "well-being")
=> `wellbeing`

2023-05-29 17:36 UTC, anvmn commented on client/src/elm/Pages/Router.elm
> +                    Just "well-being"
=> `wellbeing`

2023-05-29 17:36 UTC, anvmn commented on client/src/elm/Pages/WellBeing/View.elm
> +    div [ class "page-activity well-being" ]
=> `wellbeing`

2023-05-29 17:36 UTC, anvmn commented on client/src/assets/scss/_new.scss
> +div.page-activity.well-being{
=> `wellbeing`

2023-06-01 07:02 UTC, anvmn approved these changes

2023-06-01 07:02 UTC, merged