WIP - Child Scorecard Icons Integration
TIP-Global-Health/eheza-app pull request #787
Opened 2023-07-16 10:18 UTC by Diama1

[#778 (Comment)](https://github.com/TIP-Global-Health/eheza-app/issues/778#issuecomment-1637004528)

2023-07-16 10:42 UTC, Diama1 commented
![ncda](https://github.com/TIP-Global-Health/eheza-app/assets/32199791/7e163121-4de3-4977-9bbc-4799ebdd7281)

2023-07-18 06:26 UTC, anvmn requested changes
@Diama1 

Please have targeted interventions icon shifted a little to the right, so the circle is centered.
Thanks,

2023-07-19 09:31 UTC, Diama1 commented
![Screenshot from 2023-07-19 11-31-19](https://github.com/TIP-Global-Health/eheza-app/assets/32199791/fae25088-9522-45bf-b967-4342ccff67c3)

2023-07-19 10:36 UTC, anvmn approved these changes

2023-07-19 10:36 UTC, merged