WIP: HC Dashboard - Prenatal
TIP-Global-Health/eheza-app pull request #967
Opened 2023-12-04 13:40 UTC by anvmn

#966

2023-12-04 13:40 UTC, anvmn commented
![Selection_029](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/4d156c7e-d2c4-44bc-9b0a-b866b15dfa9b)

2023-12-04 14:22 UTC, anvmn commented
![Selection_031](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/b1ddfea5-9db6-4f8b-8054-f4896de23fb9)

2023-12-04 21:57 UTC, anvmn commented
![Selection_032](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/7d452787-cde3-4280-8448-36751116ad93)

2023-12-05 21:00 UTC, anvmn commented
![Selection_036](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/da4e3310-4987-46fa-9234-6d3461bacaaa)

2023-12-11 11:57 UTC, anvmn commented
![Selection_046](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/12845e34-3bdc-4338-af29-05ca2fcb120a)

2023-12-21 11:45 UTC, mariano-dagostino requested changes
@anvmn Looks good, but there is one thing to check.

2023-12-21 11:45 UTC, mariano-dagostino commented on client/src/elm/Pages/Dashboard/View.elm
> +                ++ newlyDiagnosesAcuteMalnutritionPregnancies
Is this repeated? @anvmn

2023-12-27 20:36 UTC, anvmn commented on client/src/elm/Pages/Dashboard/View.elm
> +                ++ newlyDiagnosesAcuteMalnutritionPregnancies
Duplicate indeed. Nice catch @mariano-dagostino

2023-12-27 20:36 UTC, merged